"""add product constraints

Revision ID: c2d578c09fa7
Revises: eda49ea28ad0
Create Date: 2026-09-23 16:10:22.208006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d578c09fa7'
down_revision: Union[str, Sequence[str], None] = 'eda49ea28ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
    "check_product_price_positive",
    "products",
    "price > 0"
)
    
    op.create_check_constraint(
    "check_product_quantity_non_negative",
    "products",
    "quantity >= 0"
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "check_product_quantity_non_negative",
        "products",
        type_="check"
    )

    op.drop_constraint(
        "check_product_price_positive",
        "products",
        type_="check"
    )